


REGISTER="//html/body/form/div[1]/button"
SLEEP="3"
# CHK_RULE="//*[@id="rule"]"

FIRSTNAME="id:fname"
LASTNAME="id:lname"
NICKNAME="id:nname"
USERNAME="id:user"
PASSWORD="id:psw"
CONFIRM_PASSWORD="id:psw_re"
TELEPHONE="id:telephone"
ADDRESS="id:address"
EMAIL="id:email"
BIRTHDAY="id:birthday"

TXT_FIRSTNAME="test"
TXT_LASTNAME="program"
TXT_NICKNAME="protest"
TEXT_USERNAME="testuser"
TEXT_PASSWORD="testtest"
TEXT="testtest"
TXT_TELEPHONE="0812345678"
TXT_ADDRESS="bangkok"
TXT_EMAIL="test@gmail.com"
TXT_BIRTHDAY="07/22/2022"

# TXT_NO_FIRSTNAME=""
# TXT_NO_LASTNAME=""
# TEXT_NO_USERNAME=""
# TEXT_NO_PASSWORD=""
TEXT_INCORRECT="test1234"
# TXT_NO_TELEPHONE=""
TEXT_INCORRECT_EMAIL="testtest"
# TXT_NO_BIRTHDAY=""